"""0007_update_book_file_length

Revision ID: e31674f245db
Revises: 3f2ab1c32cba
Create Date: 2025-06-16 18:04:39.418199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31674f245db'
down_revision: Union[str, None] = '3f2ab1c32cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast_table')
    op.alter_column('books', 'preview_image',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.alter_column('books', 'file',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'file',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('books', 'preview_image',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.create_table('fast_table',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__fast_table')),
    sa.UniqueConstraint('name', name=op.f('uq__fast_table__name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
