"""0004_all_pdf_history_time

Revision ID: 3c951d1adafe
Revises: 4185e1869021
Create Date: 2024-04-28 13:28:41.385762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c951d1adafe'
down_revision: Union[str, None] = '4185e1869021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('pdf_history_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_data', 'pdf_history_updated_at')
    # ### end Alembic commands ###
