"""0006_update_pdf_history_length

Revision ID: 3f2ab1c32cba
Revises: dd923cf422ad
Create Date: 2025-06-06 17:27:26.044165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2ab1c32cba'
down_revision: Union[str, None] = 'dd923cf422ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_data', 'pdf_history',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_data', 'pdf_history',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
