"""0002_add_favorites_and_read_books

Revision ID: 7d8b3af9b25a
Revises: c4ba516667de
Create Date: 2024-04-04 17:15:41.501543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8b3af9b25a'
down_revision: Union[str, None] = 'c4ba516667de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk__books_read__book_id__books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__books_read__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__books_read'))
    )
    op.create_table('favorite_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk__favorite_books__book_id__books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__favorite_books__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__favorite_books'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_books')
    op.drop_table('books_read')
    # ### end Alembic commands ###
