"""0005_alter_preview_image_length

Revision ID: b072bd343d98
Revises: 3c951d1adafe
Create Date: 2024-04-30 22:33:45.413070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b072bd343d98'
down_revision: Union[str, None] = '3c951d1adafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'preview_image',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'preview_image',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
