"""empty message

Revision ID: 155b76877759
Revises: e31674f245db
Create Date: 2025-06-16 23:35:43.921586

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '155b76877759'
down_revision: str | None = 'e31674f245db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelf', sa.Column('private', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookshelf', 'private')
    # ### end Alembic commands ###
