"""0010_refresh_tokens

Revision ID: 7a696e6810ea
Revises: 155b76877759
Create Date: 2025-10-04 18:33:20.009956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a696e6810ea'
down_revision: Union[str, None] = '155b76877759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=150), nullable=False),
    sa.Column('issued_at', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__refresh_tokens__user_id__users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq__refresh_tokens__token_hash'))
    )
    op.alter_column('books_read', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books_read', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_books', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorite_books', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_books', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorite_books', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books_read', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books_read', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
